[package]
name = "kde_diffusion"
version = "0.1.0"
edition = "2021"

[dependencies]
argmin = "0.10.0"
ndarray = "0.16.1"
argmin-observer-slog = "0.1.0"
rustdct = "0.7.1"

[dev-dependencies]
ndarray-npy = "0.9.1"
rand = "0.9.0-beta.3"
rand_distr = "0.5.0-beta.3"
plotly = "0.12"